### ISSUE TITLE
TypeError: 'IOHandles' object is not subscriptable

### ISSUE THREAD

**Issue by aakashsur** [open2c/cooler#248]
When attempting `cooler cload` I get this error -

> Traceback (most recent call last):
  File "/mmfs1/home/asur/.virtual/python-3/bin/cooler", line 8, in <module>
    sys.exit(cli())
  File "/mmfs1/home/asur/.virtual/python-3/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mmfs1/home/asur/.virtual/python-3/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mmfs1/home/asur/.virtual/python-3/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mmfs1/home/asur/.virtual/python-3/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mmfs1/home/asur/.virtual/python-3/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mmfs1/home/asur/.virtual/python-3/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mmfs1/home/asur/.virtual/python-3/lib/python3.9/site-packages/cooler/cli/cload.py", line 546, in pairs
    f_in = get_handle(pairs_path, mode='r', compression='infer')[0]
TypeError: 'IOHandles' object is not subscriptable

It looks like this has already been fixed in the repo to deal with the newest version of pandas I presume. I suppose then it just hasn't been pushed in a release to pypi yet. Just posting for visibility.

**Comment by nvictus** [comment]
Thank you for posting! A patch version has just been released.
