### ISSUE TITLE
The correct format for cooler cload pairs

### ISSUE THREAD

**Issue by yanchunzhang** [open2c/cooler#258]
Hi, I'm trying convert merged_nodups.txt file from juicer to .cool file.

I used those parameters:
 cooler cload pairs --assembly mm10 \
-c1 2 -p1 3 -c2 6 -p2 7 \
--chunksize 10000

While got an error:
Traceback (most recent call last):
  File "/home/ch220811/software/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/home/ch220811/software/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ch220811/software/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ch220811/software/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ch220811/software/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ch220811/software/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ch220811/software/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ch220811/software/lib/python3.6/site-packages/cooler/cli/cload.py", line 593, in pairs
    ordered=False
  File "/home/ch220811/software/lib/python3.6/site-packages/cooler/create/_create.py", line 1058, in create_cooler
    max_merge=max_merge,
  File "/home/ch220811/software/lib/python3.6/site-packages/cooler/create/_create.py", line 720, in create_from_unordered
    for i, chunk in enumerate(chunks):
  File "/home/ch220811/software/lib/python3.6/site-packages/pandas/io/parsers.py", line 1173, in __next__
    return self.get_chunk()
  File "/home/ch220811/software/lib/python3.6/site-packages/pandas/io/parsers.py", line 1232, in get_chunk
    return self.read(nrows=size)
  File "/home/ch220811/software/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/ch220811/software/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 874, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 941, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1002, in pandas._libs.parsers.TextReader._convert_column_data
pandas.errors.ParserError: Too many columns specified: expected 4 and found 1

Do you know why this happend?
Is it because I cannnot using the file from juicer?

Thanks,
Yanchun

**Comment by Phlya** [comment]
Can you post the first few lines of your file?

**Comment by yanchunzhang** [comment]
> Can you post the first few lines of your file?

I figured out why. That's because the line is separated by blank instead of tab...
Thanks for you reply!

**Comment by Phlya** [comment]
Was exactly my guess!

**Comment by Phlya** [comment]
Just in case, you can change the delimiter on the fly, and pipe the output into parse.
