### ISSUE TITLE
cooler cload pairs error - Too many columns specified: expected 2 and found 1

### ISSUE THREAD

**Issue by yeroslaviz** [open2c/cooler#277]
I'm trying to run `cooler cload pairs` with output files from `pairtools`. When running this command:

```
cat File.lowcov.pairs | sed '/^#/!s/#/N/g' | cooler cload pairs --metadata meta/File.stats.json -c1 2 -p1 3 -c2 4 -p2 5 hg19_CHROM_SIZE_FILE:1000000 - cload.pairs/File.1000000.cool
```

I get the following error:

```
Traceback (most recent call last):
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/cooler/cli/cload.py", line 450, in pairs
    chromsizes, bins = parse_bins(bins)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/cooler/cli/_util.py", line 115, in parse_bins
    chromsizes = util.read_chromsizes(chromsizes_file, all_names=True)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/cooler/util.py", line 236, in read_chromsizes
    chromtable = pd.read_csv(
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1254, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/fs/home/yeroslaviz/miniconda3/envs/cooler/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 805, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 883, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 945, in pandas._libs.parsers.TextReader._convert_column_data
pandas.errors.ParserError: Too many columns specified: expected 2 and found 1
```

The first few lines of my input file are:

```
## pairs format v1.0.0
#sorted: chr1-chr2-pos1-pos2
#shape: upper triangle
#genome_assembly: hg19
#chromsize: 1 248956422
#chromsize: 10 133797422
#chromsize: 11 135086622
#chromsize: 12 133275309
#chromsize: 13 114364328
...
#columns: readID chrom1 pos1 chrom2 pos2 strand1 strand2 pair_type
D00689:490:CD7AMANXX:7:2201:6192:55306  1       4318359 1       4318405 +       +       UU
D00689:490:CD7AMANXX:7:2212:18275:75153 1       6935482 1       6935620 +       -       UU
D00689:490:CD7AMANXX:7:1209:10385:75087 1       6985531 1       6985664 +       -       UU
D00689:490:CD7AMANXX:7:1116:7430:21389  1       7370210 1       7370453 +       -       UU
```

Even though it won't show here the file seems to be tab-delimited, so I do have the correct four columns for the chr/pos combination.

Any Idea, why I get this error?

thanks

Assa

**Comment by yeroslaviz** [comment]
sorry for posting too fast. i have found the problem. 

If anyone encounter similar problems. It was the chrom.sizes file. It must be also tab-delimited, bit somehow it was only spaces.
