### ISSUE TITLE
Import Error in h5py

### ISSUE THREAD

**Issue by MyBiscuit** [open2c/cooler#291]
I cannot create a cool file due to some issue with h5py.
I used conda to install cooler:
` $ conda install -c conda-forge -c bioconda cooler`

This is the error I get when running cooler cload pairix:

```
Traceback (most recent call last):
  File "/ext3/miniconda3/bin/cooler", line 6, in <module>
    from cooler.cli import cli
  File "/ext3/miniconda3/lib/python3.9/site-packages/cooler/__init__.py", line 14, in <module>
    from .api import Cooler, annotate
  File "/ext3/miniconda3/lib/python3.9/site-packages/cooler/api.py", line 11, in <module>
    import h5py
  File "/ext3/miniconda3/lib/python3.9/site-packages/h5py/__init__.py", line 33, in <module>
    from . import version
  File "/ext3/miniconda3/lib/python3.9/site-packages/h5py/version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: /ext3/miniconda3/lib/python3.9/site-packages/h5py/defs.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pget_fapl_direct
```

I also tried to separately install h5py with
`  $ conda install h5py`
and then run cooler, but ended up with the same error.

**Comment by Phlya** [comment]
Can you try installing h5py using conda before installing cooler, in a new environment?

**Comment by BeetleMilk** [comment]
It worked. Cooler ran with no errors. Thank you!

**Comment by Phlya** [comment]
Happy to help!
