### ISSUE TITLE
Solution for UnicodeDecodeError cooler cload pairs

### ISSUE THREAD

**Issue by ericmalekos** [open2c/cooler#292]
Hello, I'm trying to convert some "pairs" files to "cool" format. I have been successful for 4/5 pairs files but the fifth is throwing an issue related to encoding. This seems odd given that all of the files are from the source. Also, it seems that a large portion of the file is processed correctly before an error is raised - maybe there is a way I can find and remove the offending line(s) in the pairs file?

My command:
`cooler cload pairs hg19.chrom.sizes:1000 --zero-based -c1 2 -p1 3 -c2 4 -p2 5 THP-merge_R1.pairs.txt.gz THP-merge_R1_1kb.cool
`

Output:

```
INFO:cooler.create:Writing chunk 0: emalekos/Hi-C/tmpa2myad4_.multi.cool::0
INFO:cooler.create:Creating cooler at "/emalekos/Hi-C/tmpa2myad4_.multi.cool::/0"
INFO:cooler.create:Writing chroms
INFO:cooler.create:Writing bins
INFO:cooler.create:Writing pixels
INFO:cooler.create:Writing indexes
INFO:cooler.create:Writing info
...
INFO:cooler.create:Writing chunk 26: emalekos/Hi-C/tmpa2myad4_.multi.cool::26
INFO:cooler.create:Creating cooler at "/emalekos/Hi-C/tmpa2myad4_.multi.cool::/26"
INFO:cooler.create:Writing chroms
INFO:cooler.create:Writing bins
INFO:cooler.create:Writing pixels
INFO:cooler.create:Writing indexes
INFO:cooler.create:Writing info
Traceback (most recent call last):
  File "/public/home/emalekos/miniconda3/envs/cooler/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/cooler/cli/cload.py", line 580, in pairs
    create_cooler(
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/cooler/create/_create.py", line 1039, in create_cooler
    create_from_unordered(
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/cooler/create/_create.py", line 720, in create_from_unordered
    for i, chunk in enumerate(chunks):
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1702, in __next__
    return self.get_chunk()
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1804, in get_chunk
    return self.read(nrows=size)
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1772, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/public/home/emalekos/miniconda3/envs/cooler/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 243, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 820, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1037, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1068, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1230, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1246, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1444, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 0: invalid start byte
```

Appreciate any help or insight!

**Comment by thomas-reimonn** [comment]
Sorry for the very late response. Indeed it appears the pairs file is corrupt. If this is still an issue, we can help find the problem. For example, you could try running pandas.read_csv in [iterator](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) mode (iterator=True and chunksize=...) and track the line indexes until you encounter this same error.
