### ISSUE TITLE
cooler cload pairs load .pairs file with customized bin

### ISSUE THREAD

**Issue by KunFang93** [open2c/cooler#295]
Hi,

Thanks for providing this awesome tools! It's very user friendly and highly flexiable~

I would like to inquire if there is a way to build .cool file with customized bin (genomic region) instead of universal interval?
For example, I would like to build matrix with specific loci:
```
chr1 10610 20456
chr1 21789 34567
chr1 38901 45230
......
```
instead of with universal interval.
```
chr1 1 10000
chr1 10001 20000
......
```

I knew this might be a rare way to deal with Hi-C data but I would like to inquire if there is way to workaround? Please let me know if any additional information is needed. Thanks for your time and help in advance!

Best,
Kun

**Comment by KunFang93** [comment]
Hi

I realized that I could pass ```BINS``` with BED file in ```cooler load pairs```. Then I tried command 
```
cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 --assembly hg38 loc.bed test_mapped.pairs test.hg38.nuc.cool
```

However, this command ends with the following error:
```
Traceback (most recent call last):
  File "/data/kun/miniconda3/envs/NucOrg/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/cooler/cli/cload.py", line 580, in pairs
    create_cooler(
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/cooler/create/_create.py", line 1039, in create_cooler
    create_from_unordered(
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/cooler/create/_create.py", line 720, in create_from_unordered
    for i, chunk in enumerate(chunks):
  File "cytoolz/functoolz.pyx", line 502, in cytoolz.functoolz.Compose.__call__
  File "/data/kun/miniconda3/envs/NucOrg/lib/python3.10/site-packages/cooler/create/_ingest.py", line 140, in _sanitize_records
    raise BadInputError(
cooler.create._ingest.BadInputError: Found an anchor position exceeding chromosome length:
	chrom1	pos1	chrom2	pos2
696416	chr1	45066869	chr4	190177898
740303	chr1	3272013	chrX	155718547
740357	chr1	9710779	chrX	155718938
740699	chr1	45647214	chrX	155893915
740980	chr1	72610806	chrX	155828957
```

I have check the genome size of hg38 but looks like these anchors are not exceeding chromosome length. So I wondered if there is a way to solve the bug? 

The content in the loc.bed 
```
chr1	10071	10111
chr1	10181	10331
chr1	10451	10551
chr1	12981	13051
chr1	13101	13171
chr1	14841	15031
chr1	16141	16211
chr1	16271	16421
chr1	16481	16541
chr1	16821	16891
.....
chrX	155699161	155699241
chrX	155699371	155699461
chrX	155699561	155699671
chrX	155699791	155699911
chrX	155700131	155700201
chrX	155700331	155700401
chrX	155700461	155700511
chrX	155700621	155700721
chrY	14956541	14956601
chrY	14956661	14956741
```

Please let me know if any additional information is needed. Thanks for your help!

Best,
Kun

**Comment by KunFang93** [comment]
Solution: add a line containing chrom size to the bed file, e.g.,
```
chr1 249698942 249698942
```
