### ISSUE TITLE
cooler cload tabix with single proc raise UnboundLocalError

### ISSUE THREAD

**Issue by lldelisle** [open2c/cooler#315]
Hi,
Here is the error:
```
Traceback (most recent call last):
  File "/home/ldelisle/miniconda2/envs/hic202302/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/home/ldelisle/miniconda2/envs/hic202302/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ldelisle/miniconda2/envs/hic202302/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ldelisle/miniconda2/envs/hic202302/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ldelisle/miniconda2/envs/hic202302/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ldelisle/miniconda2/envs/hic202302/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ldelisle/miniconda2/envs/hic202302/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ldelisle/miniconda2/envs/hic202302/lib/python3.10/site-packages/cooler/cli/cload.py", line 234, in tabix
    map=map,
UnboundLocalError: local variable 'map' referenced before assignment
```

Indeed when I check the code I see:
https://github.com/open2c/cooler/blob/6b174f1a7c63c6c2bf11890ab20bfed01c98e97f/cooler/cli/cload.py#L219-L222

There is no else which would initiate map.

**Comment by thomas-reimonn** [comment]
Fixed in PR #380
