### ISSUE TITLE
TypeError: 'IOHandles' object is not subscriptable

### ISSUE THREAD

**Issue by markme123** [open2c/cooler#327]
cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 fasta.fai:1000 null.pairs.gz null.pairs.cool
Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/cooler", line 10, in <module>
      sys.exit(cli())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/cli/cload.py", line 551, in pairs
      f_in = get_handle(pairs_path, mode='r', compression='infer')[0]
  TypeError: 'IOHandles' object is not subscriptable

**Comment by nvictus** [comment]
This should be fixed in the latest release v0.9.2. Please re-open if this is not the case.
