### ISSUE TITLE
New bug introduced in 0.9.2 in balance --cis-only

### ISSUE THREAD

**Issue by lldelisle** [open2c/cooler#343]
Dear cooler developers,
With cooler 0.9.1, I can do:
```
$ cooler balance --cis-only test.cool
INFO:cooler.cli.balance:Balancing "test.cool"
INFO:cooler.balance:chr10
INFO:cooler.balance:chr11
INFO:cooler.balance:chr11_gl000202_random
INFO:cooler.balance:chr12
INFO:cooler.balance:chr13
INFO:cooler.balance:chr14
INFO:cooler.balance:chr15
INFO:cooler.balance:chr16
INFO:cooler.balance:chr17_ctg5_hap1
INFO:cooler.balance:chr17
INFO:cooler.balance:chr17_gl000203_random
INFO:cooler.balance:chr17_gl000204_random
INFO:cooler.balance:chr17_gl000205_random
INFO:cooler.balance:chr17_gl000206_random
INFO:cooler.balance:chr18
INFO:cooler.balance:chr18_gl000207_random
INFO:cooler.balance:chr19
INFO:cooler.balance:chr19_gl000208_random
INFO:cooler.balance:chr19_gl000209_random
INFO:cooler.balance:chr1
INFO:cooler.balance:chr1_gl000191_random
INFO:cooler.balance:chr1_gl000192_random
INFO:cooler.balance:chr20
INFO:cooler.balance:chr21
INFO:cooler.balance:chr21_gl000210_random
INFO:cooler.balance:chr22
INFO:cooler.balance:chr2
INFO:cooler.balance:chr3
INFO:cooler.balance:chr4_ctg9_hap1
INFO:cooler.balance:chr4
INFO:cooler.balance:chr4_gl000193_random
INFO:cooler.balance:chr4_gl000194_random
INFO:cooler.balance:chr5
INFO:cooler.balance:chr6_apd_hap1
INFO:cooler.balance:chr6_cox_hap2
INFO:cooler.balance:chr6_dbb_hap3
INFO:cooler.balance:chr6
INFO:cooler.balance:chr6_mann_hap4
INFO:cooler.balance:chr6_mcf_hap5
INFO:cooler.balance:chr6_qbl_hap6
INFO:cooler.balance:chr6_ssto_hap7
INFO:cooler.balance:chr7
INFO:cooler.balance:chr7_gl000195_random
INFO:cooler.balance:chr8
INFO:cooler.balance:chr8_gl000196_random
INFO:cooler.balance:chr8_gl000197_random
INFO:cooler.balance:chr9
INFO:cooler.balance:chr9_gl000198_random
INFO:cooler.balance:chr9_gl000199_random
INFO:cooler.balance:chr9_gl000200_random
INFO:cooler.balance:chr9_gl000201_random
INFO:cooler.balance:chrM
INFO:cooler.balance:chrUn_gl000211
INFO:cooler.balance:chrUn_gl000212
INFO:cooler.balance:chrUn_gl000213
INFO:cooler.balance:chrUn_gl000214
INFO:cooler.balance:chrUn_gl000215
INFO:cooler.balance:chrUn_gl000216
INFO:cooler.balance:chrUn_gl000217
INFO:cooler.balance:chrUn_gl000218
INFO:cooler.balance:chrUn_gl000219
INFO:cooler.balance:chrUn_gl000220
INFO:cooler.balance:chrUn_gl000221
INFO:cooler.balance:chrUn_gl000222
INFO:cooler.balance:chrUn_gl000223
INFO:cooler.balance:chrUn_gl000224
INFO:cooler.balance:chrUn_gl000225
INFO:cooler.balance:chrUn_gl000226
INFO:cooler.balance:chrUn_gl000227
INFO:cooler.balance:chrUn_gl000228
INFO:cooler.balance:chrUn_gl000229
INFO:cooler.balance:chrUn_gl000230
INFO:cooler.balance:chrUn_gl000231
INFO:cooler.balance:chrUn_gl000232
INFO:cooler.balance:chrUn_gl000233
INFO:cooler.balance:chrUn_gl000234
INFO:cooler.balance:chrUn_gl000235
INFO:cooler.balance:chrUn_gl000236
INFO:cooler.balance:chrUn_gl000237
INFO:cooler.balance:chrUn_gl000238
INFO:cooler.balance:chrUn_gl000239
INFO:cooler.balance:chrUn_gl000240
INFO:cooler.balance:chrUn_gl000241
INFO:cooler.balance:chrUn_gl000242
INFO:cooler.balance:chrUn_gl000243
INFO:cooler.balance:chrUn_gl000244
INFO:cooler.balance:chrUn_gl000245
INFO:cooler.balance:chrUn_gl000246
INFO:cooler.balance:chrUn_gl000247
INFO:cooler.balance:chrUn_gl000248
INFO:cooler.balance:chrUn_gl000249
INFO:cooler.balance:chrX
INFO:cooler.balance:chrY
```
With 0.9.2 I get:
```
$ cooler balance --cis-only test.cool
INFO:cooler.cli.balance:Balancing "test.cool"
INFO:cooler.balance:chr10
INFO:cooler.balance:chr11
INFO:cooler.balance:chr11_gl000202_random
INFO:cooler.balance:chr12
INFO:cooler.balance:chr13
INFO:cooler.balance:chr14
INFO:cooler.balance:chr15
INFO:cooler.balance:chr16
INFO:cooler.balance:chr17_ctg5_hap1
INFO:cooler.balance:chr17
INFO:cooler.balance:chr17_gl000203_random
INFO:cooler.balance:chr17_gl000204_random
INFO:cooler.balance:chr17_gl000205_random
INFO:cooler.balance:chr17_gl000206_random
INFO:cooler.balance:chr18
INFO:cooler.balance:chr18_gl000207_random
INFO:cooler.balance:chr19
INFO:cooler.balance:chr19_gl000208_random
INFO:cooler.balance:chr19_gl000209_random
INFO:cooler.balance:chr1
INFO:cooler.balance:chr1_gl000191_random
INFO:cooler.balance:chr1_gl000192_random
INFO:cooler.balance:chr20
INFO:cooler.balance:chr21
INFO:cooler.balance:chr21_gl000210_random
INFO:cooler.balance:chr22
INFO:cooler.balance:chr2
INFO:cooler.balance:chr3
INFO:cooler.balance:chr4_ctg9_hap1
INFO:cooler.balance:chr4
INFO:cooler.balance:chr4_gl000193_random
INFO:cooler.balance:chr4_gl000194_random
INFO:cooler.balance:chr5
INFO:cooler.balance:chr6_apd_hap1
INFO:cooler.balance:chr6_cox_hap2
INFO:cooler.balance:chr6_dbb_hap3
INFO:cooler.balance:chr6
INFO:cooler.balance:chr6_mann_hap4
INFO:cooler.balance:chr6_mcf_hap5
INFO:cooler.balance:chr6_qbl_hap6
INFO:cooler.balance:chr6_ssto_hap7
INFO:cooler.balance:chr7
INFO:cooler.balance:chr7_gl000195_random
INFO:cooler.balance:chr8
INFO:cooler.balance:chr8_gl000196_random
INFO:cooler.balance:chr8_gl000197_random
INFO:cooler.balance:chr9
INFO:cooler.balance:chr9_gl000198_random
INFO:cooler.balance:chr9_gl000199_random
INFO:cooler.balance:chr9_gl000200_random
INFO:cooler.balance:chr9_gl000201_random
INFO:cooler.balance:chrM
INFO:cooler.balance:chrUn_gl000211
INFO:cooler.balance:chrUn_gl000212
INFO:cooler.balance:chrUn_gl000213
INFO:cooler.balance:chrUn_gl000214
INFO:cooler.balance:chrUn_gl000215
INFO:cooler.balance:chrUn_gl000216
INFO:cooler.balance:chrUn_gl000217
INFO:cooler.balance:chrUn_gl000218
INFO:cooler.balance:chrUn_gl000219
INFO:cooler.balance:chrUn_gl000220
INFO:cooler.balance:chrUn_gl000221
INFO:cooler.balance:chrUn_gl000222
INFO:cooler.balance:chrUn_gl000223
INFO:cooler.balance:chrUn_gl000224
INFO:cooler.balance:chrUn_gl000225
INFO:cooler.balance:chrUn_gl000226
INFO:cooler.balance:chrUn_gl000227
INFO:cooler.balance:chrUn_gl000228
INFO:cooler.balance:chrUn_gl000229
INFO:cooler.balance:chrUn_gl000230
INFO:cooler.balance:chrUn_gl000231
INFO:cooler.balance:chrUn_gl000232
INFO:cooler.balance:chrUn_gl000233
INFO:cooler.balance:chrUn_gl000234
INFO:cooler.balance:chrUn_gl000235
INFO:cooler.balance:chrUn_gl000236
INFO:cooler.balance:chrUn_gl000237
INFO:cooler.balance:chrUn_gl000238
INFO:cooler.balance:chrUn_gl000239
INFO:cooler.balance:chrUn_gl000240
INFO:cooler.balance:chrUn_gl000241
INFO:cooler.balance:chrUn_gl000242
INFO:cooler.balance:chrUn_gl000243
INFO:cooler.balance:chrUn_gl000244
INFO:cooler.balance:chrUn_gl000245
INFO:cooler.balance:chrUn_gl000246
INFO:cooler.balance:chrUn_gl000247
INFO:cooler.balance:chrUn_gl000248
INFO:cooler.balance:chrUn_gl000249
INFO:cooler.balance:chrX
INFO:cooler.balance:chrY
Traceback (most recent call last):
  File "/home/ldelisle/.conda/envs/lastVersion/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ldelisle/.conda/envs/lastVersion/lib/python3.9/site-packages/cooler/cli/balance.py", line 228, in balance
    if not stats['converged']:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Here is the cool file I used.
[test.cool.zip](https://github.com/open2c/cooler/files/12575524/test.cool.zip)

Installation with conda with:
```
$ conda list | grep numpy
numpy                     1.23.5           py39h3d75532_0    conda-forge
$ conda list | grep cooler
cooler                    0.9.2              pyh7cba7a3_0    bioconda
$ python --version
Python 3.9.15
```

**Comment by nvictus** [comment]
Hi Lucile! This seems to be the regression addressed in #334. We'll release the patch soon.

**Comment by lldelisle** [comment]
Thanks, I missed it.

**Comment by nvictus** [comment]
v0.9.3 is now published on PyPI

**Comment by lldelisle** [comment]
Great. Thanks. I needed the conda package but I see it is also released.
