### ISSUE TITLE
Cooler cloud pairs error 

### ISSUE THREAD

**Issue by luantune** [open2c/cooler#365]
Hello I am running cooler inside beluga cluster of compute canada and I have been running into an error. 

I am currently running: 
cooler cload pairs  -c1 2 -p1 3 -c2 4 -p2 5 /scratch/T427_63_2018_no_unitigs_genome.sizes:1000 /scratch/C107-II_digested_aligned_3.pairs C107-II.cool 

get the error: 
NFO:cooler.create:Writing chunk 0: /lustre04/scratch/luantune/tmpexd7xedf.multi.cool::0 

INFO:cooler.create:Creating cooler at "/lustre04/scratch/luantune/tmpexd7xedf.multi.cool::/0" 

INFO:cooler.create:Writing chroms 

INFO:cooler.create:Writing bins 

INFO:cooler.create:Writing pixels 

INFO:cooler.create:Writing indexes 

INFO:cooler.create:Writing info 

INFO:cooler.create:Writing chunk 1: /lustre04/scratch/luantune/tmpexd7xedf.multi.cool::1 

INFO:cooler.create:Creating cooler at "/lustre04/scratch/luantune/tmpexd7xedf.multi.cool::/1" 

INFO:cooler.create:Writing chroms 

INFO:cooler.create:Writing bins 

INFO:cooler.create:Writing pixels 

INFO:cooler.create:Writing indexes 

INFO:cooler.create:Writing info 

INFO:cooler.create:Merging into C107-II.cool 

INFO:cooler.create:Creating cooler at "C107-II.cool::/" 

INFO:cooler.create:Writing chroms 

INFO:cooler.create:Writing bins 

INFO:cooler.create:Writing pixels 

INFO:cooler.reduce:nnzs: [0, 0] 

INFO:cooler.reduce:current: [0, 0] 

Traceback (most recent call last): 

  File "/home/luantune/.local/bin/cooler", line 8, in <module> 

    sys.exit(cli()) 

  File "/home/luantune/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__ 

    return self.main(*args, **kwargs) 

  File "/home/luantune/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main 

    rv = self.invoke(ctx) 

  File "/home/luantune/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke 

    return _process_result(sub_ctx.command.invoke(sub_ctx)) 

  File "/home/luantune/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke 

    return _process_result(sub_ctx.command.invoke(sub_ctx)) 

  File "/home/luantune/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke 

    return ctx.invoke(self.callback, **ctx.params) 

  File "/home/luantune/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke 

    return __callback(*args, **kwargs) 

  File "/home/luantune/.local/lib/python3.9/site-packages/cooler/cli/cload.py", line 584, in pairs 

    create_cooler( 

  File "/home/luantune/.local/lib/python3.9/site-packages/cooler/create/_create.py", line 1042, in create_cooler 

    create_from_unordered( 

  File "/home/luantune/.local/lib/python3.9/site-packages/cooler/create/_create.py", line 764, in create_from_unordered 

    create(cool_uri, bins, chunks, columns=columns, dtypes=dtypes, mode=mode, **kwargs) 

  File "/home/luantune/.local/lib/python3.9/site-packages/cooler/create/_create.py", line 642, in create 

    nnz, ncontacts = write_pixels( 

  File "/home/luantune/.local/lib/python3.9/site-packages/cooler/create/_create.py", line 211, in write_pixels 

    for i, chunk in enumerate(iterable): 

  File "/home/luantune/.local/lib/python3.9/site-packages/cooler/reduce.py", line 149, in __iter__ 

    combined = pd.concat( 

  File "/home/luantune/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 380, in concat 

    op = _Concatenator( 

  File "/home/luantune/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 443, in __init__ 

    objs, keys = self._clean_keys_and_objs(objs, keys) 

  File "/home/luantune/.local/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 505, in _clean_keys_and_objs 

    raise ValueError("No objects to concatenate") 

ValueError: No objects to concatenate 

however when I use a smaller dataset: cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 tests/genome_files_igor/TriTrypDB-46_TbruceiLister427_2018_chromosome.size:1000 tests/porec_new_pipeline_trial/AllHiCN117_digested_aligned_2.pairs AllHiCN117_digested_aligned_2.cool  

i do not get an error: 
INFO:cooler.create:Writing chunk 0: /lustre04/scratch/luantune/tmpifn7xkxs.multi.cool::0 

INFO:cooler.create:Creating cooler at "/lustre04/scratch/luantune/tmpifn7xkxs.multi.cool::/0" 

INFO:cooler.create:Writing chroms 

INFO:cooler.create:Writing bins 

INFO:cooler.create:Writing pixels 

INFO:cooler.create:Writing indexes 

INFO:cooler.create:Writing info 

INFO:cooler.create:Merging into AllHiCN117_digested_aligned_2.cool 

INFO:cooler.create:Creating cooler at "AllHiCN117_digested_aligned_2.cool::/" 

INFO:cooler.create:Writing chroms 

INFO:cooler.create:Writing bins 

INFO:cooler.create:Writing pixels 

INFO:cooler.reduce:nnzs: [91073] 

INFO:cooler.reduce:current: [91073] 

INFO:cooler.create:Writing indexes 

INFO:cooler.create:Writing info   

I can also confirm that for my larger dataset (the one I am getting the error) my .pairs file is not empty and it looks fine, exactly like the one for the smaller dataset. 

Thanks in advance, 

Luiza

**Comment by hackkr** [comment]
Hi @luantune. Did you figure out what was causing this issue? How did you resolve it? I'm currently experiencing the same thing.
