### ISSUE TITLE
ValueError: cannot safely convert passed user dtype of int64 for float64 dtyped data in column 4

### ISSUE THREAD

**Issue by sfh1111** [open2c/cooler#390]
Hi, I have run cooler successfully few times but started to get this error:
cooler cload pairs -c1 2 -p1 3 -c2 4 -p2 5 --assembly xx xx.sizes.200 merged xx.cool
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1131, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/labs/danielda/shdemf/.conda/envs/HiC/bin/cooler", line 10, in <module>
    sys.exit(cli())
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/cooler/cli/cload.py", line 584, in pairs
    create_cooler(
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/cooler/create/_create.py", line 1042, in create_cooler
    create_from_unordered(
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/cooler/create/_create.py", line 719, in create_from_unordered
    for i, chunk in enumerate(chunks):
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1624, in __next__
    return self.get_chunk()
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1733, in get_chunk
    return self.read(nrows=size)
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/labs/danielda/shdemf/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 826, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 891, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1036, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1139, in pandas._libs.parsers.TextReader._convert_tokens
ValueError: cannot safely convert passed user dtype of int64 for float64 dtyped data in column 4

**Comment by nvictus** [comment]
Your pairs file may have issues. The error says it's interpreting some part of your `-p2` column as floating point and can't convert to integer type (e.g. NaN). I would search for (1) malformed or missing values or (2) make sure the pairs file is properly tab delimited.

**Comment by nvictus** [comment]
Closing for now. Feel free to re-open if your issue isn't resolved.
