### ISSUE TITLE
Pypairix was installed but did not work.

### ISSUE THREAD

**Issue by jiehua1995** [open2c/cooler#445]
Hello, I had a problem about pairix:

```
(cooltools) zzz@zzz-server:mapping_output$ cooler cload pairix -p 84 dm.genome:1000 mapping.mapped.pairs.gz matrix_1000bp.cool
INFO:cooler.cli.cload:Using 84 cores
Traceback (most recent call last):
  File "/home/zzz/.local/bin/cooler", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zzz/.local/lib/python3.8/site-packages/cooler/cli/cload.py", line 338, in pairix
    iterator = PairixAggregator(
  File "/home/zzz/.local/lib/python3.8/site-packages/cooler/create/_ingest.py", line 804, in __init__
    raise ImportError(
ImportError: pypairix is required to read pairix-indexed files
(cooltools) zzz@zzz-server:mapping_output$ pip list | grep pairix
pypairix           0.3.8
```
I already installed cooler and cooltools via mamba, I also installed pypairix with pip. However, the command did not work.

**Comment by jiehua1995** [comment]
The problem comes from conda enviroment. Cooler was also installed somewhere else.

`/home/zzz/anaconda3/envs/cooltools/bin/cooler cload pairix -p 84 dm.genome:1000 mapping.mapped.pairs.gz matrix_1000bp.cool`

works
